name: Continuous Deployment to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
        
      - id: vars
        run: |
          TAG_SHA=$(echo $GITHUB_SHA | cut -c1-8)
          echo "tag=$TAG_SHA" >> $GITHUB_OUTPUT

              
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

              
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/junior-devops-site:${{ steps.vars.outputs.tag }}
          build-args: |
            BUILD_COMMIT_SHA=${{ steps.vars.outputs.tag }}
          
   
      - uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Przejdź do katalogu
            cd /opt/junior-devops-site
            
            # 2. Tworzenie pliku docker-compose.yml przy użyciu nowej konfiguracji HTTPS
            # ((WAŻNE: Nazwa pliku musi odpowiadać nazwie, której będziesz używać podczas  compose)
            echo "
            version: '3.8'
            services:
              web:
                image: ${{ secrets.DOCKER_USERNAME }}/junior-devops-site:${{ steps.vars.outputs.tag }}
                ports:
                  - \"80:80\"
                  - \"443:443\"
                volumes:
                  - certbot-etc:/etc/letsencrypt
                  - certbot-web:/var/www/certbot
                  - ./html:/usr/share/nginx/html
                restart: unless-stopped
              
              certbot:
                image: certbot/certbot
                volumes:
                  - certbot-etc:/etc/letsencrypt
                  - certbot-web:/var/www/certbot
                  - ./html:/var/www/html
                entrypoint: \"/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'\"
                
            volumes:
              certbot-etc:
              certbot-web:
            " > docker-compose.yml
            
            # 3. Zastosowanie
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d --remove-orphans
            sleep 15
            CONTAINER_ID=$(docker compose -f docker-compose.yml ps -q web)
            docker cp /opt/junior-devops-site/nginx.final.conf $CONTAINER_ID:/etc/nginx/conf.d/default.conf
            docker exec $CONTAINER_ID nginx -s reload
            docker ps            